In [5]:
import pandas as pd
import requests
from io import StringIO

In [6]:
df_nger = pd.read_csv("NGER.ID0243.csv")

df_accredited = pd.read_csv("power-stations-and-projects-accredited.csv")
df_committed = pd.read_csv("power-stations-and-projects-committed.csv")
df_probable = pd.read_csv("power-stations-and-projects-probable.csv")

In [7]:
abs_url = "https://data.api.abs.gov.au/rest/data/ABS,ABS_REGIONAL_ASGS2021,/..AUS.A?startPeriod=2020&dimensionAtObservation=AllDimensions"

headers = {
    "Accept": "application/vnd.sdmx.data+csv;labels=both"
}

response = requests.get(abs_url, headers=headers, timeout=60)
response.raise_for_status()

df_abs = pd.read_csv(StringIO(response.text))

In [8]:
print("NGER shape:", df_nger.shape)
display(df_nger.head())

NGER shape: (775, 14)

,Reporting entity,Facility name,Type,State,Electricity production GJ,Electricity production MWh,Total scope 1 emissions t CO2 e,Total scope 2 emissions t CO2 e,Total emissions t CO2 e,Emission intensity t CO2 e MWh,Grid connected,Grid,Primary fuel,Important notes
0,ACCIONA ENERGY OCEANIA PTY LTD,Cathedral Rocks Wind Farm,F,SA,481948,133874,57,127.0,184,0.0,On,NEM,Wind,-
1,ACCIONA ENERGY OCEANIA PTY LTD,Gunning Wind Farm,F,NSW,491409,136502,50,218.0,268,0.0,On,NEM,Wind,-
2,ACCIONA ENERGY OCEANIA PTY LTD,Mortlake South Wind Farm,F,VIC,1019352,283153,202,1128.0,1330,0.0,On,NEM,Wind,-
3,ACCIONA ENERGY OCEANIA PTY LTD,Mt Gellibrand Wind Farm,F,VIC,1025451,284847,99,1273.0,1372,0.0,On,NEM,Wind,-
4,ACCIONA ENERGY OCEANIA PTY LTD,Waubra Wind Farm,F,VIC,1954964,543046,186,1114.0,1300,0.0,On,NEM,Wind,-

In [9]:
print("Accredited shape:", df_accredited.shape)
display(df_accredited.head())

Accredited shape: (36, 8)

,Accreditation code,Power station name,State,Postcode,Installed capacity (MW),Fuel Source (s),Accreditation start date,Approval date
0,SRPXQLO8,DONS FORT - SOLAR W SGU - QLD,QLD,4660,0.421,Solar,21/10/2025,6/01/2026
1,SRPYNSK0,Mintus Coles - Solar w SGU- NSW,NSW,2153,0.190,Solar,9/12/2025,6/01/2026
2,SRPXQLP1,Ventora - Acacia Ridge - Solar - QLD,QLD,4110,0.162,Solar,17/11/2025,6/01/2026
3,SRPYNSK3,Bayside Aged Care - Solar - Morisset - NSW,NSW,2264,0.140,Solar,16/12/2025,8/01/2026
4,SRPVWAQ0,Matrix Composites and Engineering Pty Ltd - So...,WA,6166,0.850,Solar,17/12/2025,8/01/2026

In [10]:
print("Committed shape:", df_committed.shape)
display(df_committed.head())

Committed shape: (36, 5)

,Project Name,State,MW Capacity,Fuel Source,Committed Date (Month/Year)
0,East Rockingham Resource Recovery Facility,WA,29.0,Biomass,Dec-2019
1,Mangalore Renewable Energy Project,VIC,5.0,Solar,Sep-2021
2,Orange Community Renewable Energy Park,NSW,5.0,Solar,Jul-2022
3,Moorebank Logistics Park,NSW,60.0,Solar,Sep-2022
4,Kidston Pumped Hydro Storage Project,QLD,250.0,Hydro,Jul-2023

In [11]:
print("Probable shape:", df_probable.shape)
display(df_probable.head())

Probable shape: (59, 4)

              Probable Projects State  MW Capacity Fuel Source
0        Barnawartha Solar Farm    VIC      64.000       Solar
1             Barwon solar farm    VIC     250.000       Solar
2            Bell Bay Wind Farm    TAS     224.000        Wind
3  Bendemeer Energy Hub - Solar    NSW     252.000       Solar
4      Binningup Solar Facility     WA      75.000       Solar

In [12]:
print("NGER columns:")
display(df_nger.columns)

print("Accredited columns:")
display(df_accredited.columns)

print("Committed columns:")
display(df_committed.columns)

print("Probable columns:")
display(df_probable.columns)

print("ABS columns:")
display(df_abs.columns)

NGER columns:

Index(['Reporting entity', 'Facility name', 'Type', 'State',
       'Electricity production GJ', 'Electricity production MWh',
       'Total scope 1 emissions t CO2 e', 'Total scope 2 emissions t CO2 e',
       'Total emissions t CO2 e', 'Emission intensity t CO2 e MWh',
       'Grid connected', 'Grid', 'Primary fuel', 'Important notes'],
      dtype='object')

Accredited columns:

Index(['Accreditation code', 'Power station name', 'State', 'Postcode',
       'Installed capacity (MW)', 'Fuel Source (s)',
       'Accreditation start date', 'Approval date'],
      dtype='object')

Committed columns:

Index(['Project Name', 'State ', 'MW Capacity', 'Fuel Source',
       'Committed Date (Month/Year)'],
      dtype='object')

Probable columns:

Index(['Probable Projects', 'State ', 'MW Capacity', 'Fuel Source'], dtype='object')

ABS columns:

Index(['DATAFLOW', 'MEASURE: Data Item', 'REGIONTYPE: Region Type',
       'ASGS_2021: Region', 'FREQUENCY: Frequency', 'TIME_PERIOD: Time Period',
       'OBS_VALUE', 'UNIT_MEASURE: Unit of Measure',
       'UNIT_MULT: Unit of Multiplier', 'OBS_STATUS: Observation Status',
       'OBS_COMMENT: Observation Comment'],
      dtype='object')